name: Release Builds

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/my-build-action.yml
    if: startsWith(github.ref, 'refs/tags/')
    with:
      name: 'Release'
      release: true
      minify: true
    secrets: inherit
