name: Release Builds

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      release_channel:
        description: 'Release channel'
        required: true
        default: release
        type: choice
        options:
          - release
          - nightly

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/my-build-action.yml
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    with:
      name: ${{ inputs.release_channel == 'nightly' && 'Nightly' || 'Release' }}
      release: ${{ startsWith(github.ref, 'refs/tags/') && inputs.release_channel != 'nightly' }}
      nightly_release: ${{ github.event_name == 'workflow_dispatch' && inputs.release_channel == 'nightly' }}
      minify: true
    secrets: inherit
